name: Hello World Pipeline
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  say-hello:
    runs-on:ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out your code

      - name: Print Hello World
        run: echo "Hello, World! 🎉 This is my first GitHub Actions workflow!"
